export interface Lookups {
    "solution": string;
    "vulnerability_id#0": string;
    "vulnerability_title#1": string;
    "cvss2_score#2": number;
    "cvss3_score#3": string;
    "risk_score#4": number;
    "vulnerability_publish_date#5": string;
    "vulnerability_first_discovered_date#6": string;
    "asset_name#7": string;
    "ip_address#8": string;
    "asset_type#9": string;
    "mac_address#10": string;
    "containers": number;
    "assessment_data_source#11": string;
    "last_data_collection#12": string;
    "credentials_succeeded#13": boolean;
    "remediated": boolean;
    "proof": string;
    "key": string;
    "port": string;
    "protocol": string;
    "operating_system_certainty#14": number;
    "operating_system_vendor#15": string;
    "operating_system_product#16": string;
    "operating_system_version#17": string;
    "deleted_time#18": string;
    "partition_0"?: string;
}